### ISSUE TITLE
Chinese calendar doesn't add leading zero to intercalary months

### ISSUE THREAD

**Issue by alexcjohnson** [alexcjohnson/world-calendars#4]
@n-riesco a little issue - for regular months if I do `cDate.formatDate('yyyy-mm-dd')` I get a leading zero on the month (but not with `'yyyy-m-dd'`) but for intercalary months there is no difference between `m` and `mm`

```js
> cc.newDate(1995,7,1).formatDate('yyyy-m-dd')
'1995-8-01'
> cc.newDate(1995,8,1).formatDate('yyyy-m-dd')
'1995-8i-01'
> cc.newDate(1995,7,1).formatDate('yyyy-mm-dd')
'1995-08-01'
> cc.newDate(1995,8,1).formatDate('yyyy-mm-dd')
'1995-8i-01'
```

**Comment by n-riesco** [comment]
That was a bad decision from my side. I'll fix it now.
